### ISSUE TITLE
Set up route for importing data from retrobiohub

### ISSUE THREAD

**Issue by StephanM87** [BioCatHub/bch_RetroBioHub#9]
# Requesting JSON from Miniomongo to BioCatHub

Since in #5 the connection to the database was succesful and the biocathub enzyme object is uploaded to the minimongo, it can also now be requested to be imported to biocathub:

![grafik](https://user-images.githubusercontent.com/48381090/150507698-8a47a0a7-2c9a-44c6-9795-0a2e8fb74542.png)

**Comment by StephanM87** [comment]
# Route for MiniMongo was created:

https://github.com/BioCatHub/bch_RetroBioHub/blob/0ef1995181562885ffe0e7360f3284ccb06770e2/retrobiohub/mini_mongo_query.py#L23-L37

## ToDo

- [x] Pass Datrabase id to the query function
- [x] return database entry
- [x] add exceptions if no database entry is available or no id is passed
